### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by gufrankhan1988** [Independer/wcfdataannotations#10]
Independer.WCFDataAnnotations.ValidateDataAnnotationsBehavior.GetParameterInfo(String operationName, IEnumerable`1 contractOperations)

I am having multiple types of binding for same contract

<endpoint binding="basicHttpBinding" contract="MyNameSpace.IMyService" />
        <endpoint address="local" binding="wsHttpBinding" bindingConfiguration="localWSHttpBinding" contract="MyNameSpace.IMyService" />

**Comment by istvan86-nagy** [comment]
Create a pull request for fixing it #11

**Comment by istvan86-nagy** [comment]
The issue is fixed, Nuget packages are updated (version 1.2.0)

- https://www.nuget.org/packages/Independer.WCFDataAnnotations
- https://www.nuget.org/packages/Independer.WCFDataAnnotations-Signed/

Thanks for reporting the bug @gufrankhan1988!
