### ISSUE TITLE
Missing strong name on "Signed" NuGet package version 1.2.0

### ISSUE THREAD

**Issue by PMoski** [Independer/wcfdataannotations#12]
The new release of Independer.WCFDataAnnotations-Signed 1.2.0 actually doesn't have any strong name.

Thanks,
Moski

**Comment by istvan86-nagy** [comment]
Hi @PMoski,

I am sorry, but somehow I totally missed on your issue, but now I fixed it and I have just uploaded a new version (1.2.0.1) with the correct/signed package.

I am sorry for the long waiting.

Regards,
Istvan
