### ISSUE TITLE
Validation of nested collections

### ISSUE THREAD

**Issue by schh** [Independer/wcfdataannotations#7]
Hi,

I got very happy when i saw your fork as i need to validate nested collections within my serviceoperation argument types. But im not getting it to work. i have the following class.

```

[DataContract(IsReference = true)]
public class MyDto : MyBase
{
   [DataMember]
   [Required]
   public string OrderNo { get; set; }
   
   [DataMember]
   public ICollection<MySubDto> MySubDtoCollection = new  List<MySubDto>();
}

And my subcollection class:

[DataContract(IsReference = true)]
public class MySubDto : IValidatableObject
{
    [DataMember]
    [Required]
    public string IssueNo { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        throw new NotImplementedException();
    }
}

```

My service implements [ValidateDataAnnotationsBehavior] and my required attributes etc. work, but only for for MyDto but not for MySubDto. The Validate method is never called on MySubDto, i tried declaring the collectionproperty as IEnumerable, List etc but it does not work.

Thanks you

**Comment by istvan86-nagy** [comment]
Hi @schh,

I have just looked into your problem and the reason why the validation doesn't work for you that the "MySubDtoCollection" isn't a property. If you turn it into a property it will work as expected.

```
[DataContract(IsReference = true)]
public class MyDto : MyBase
{
   [DataMember]
   [Required]
   public string OrderNo { get; set; }
   
   [DataMember]
   public ICollection<MySubDto> MySubDtoCollection { get; set; } = new  List<MySubDto>();
}

And my subcollection class:

[DataContract(IsReference = true)]
public class MySubDto : IValidatableObject
{
    [DataMember]
    [Required]
    public string IssueNo { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        throw new NotImplementedException();
    }
}
```

Best Regards,
István

**Comment by schh** [comment]
Wow what a silly mistake, sorry for wasting your time. Thanks
